language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t chaka/docker-react -f Dockerfile.dev .

script:
  - docker run chaka/docker-react npm run test -- --coverage
